### ISSUE TITLE
Kurzreview

### ISSUE THREAD

**Issue by signalwerk** [pascaleva/portfolio#1]
## Hallo Pascale
Ich habe mir kurz dein Portfolio durchgeschaut. Ich habe nur kurz drauf geschaut, da ich davon ausgehe, dass du noch nicht fertig bist. Hier vielleicht ein paar Inputs (eher technisch):

* Du hast jetzt etwa 90 Zeichen pro Zeile. Ist eher lang. Vielleicht einfach der Grundtext noch ein Px grösser?
* Deine Zwischentitel sind nun versal, "grau" und stehen eng beisammen. In Kombination erschwert dies die Lesbarkeit. Ich würde Versalien eigentlich immer sperren. [→ letter-spacing](https://www.w3schools.com/cssref/pr_text_letter-spacing.asp)
* In der inhaltlichen Abfolge kannst du dir ja noch überlegen, ob du ein/das Endprodukt vielleicht schon an den Anfang stellen willst um die Leute mit zu nehmen, die nach 2 screens scrollen schon raus sind... 
* Oder eventuell baust du noch ein Inhalts verzeichnis ganz an den Anfang um runter zu springen. Dazu kannst du zum Beispiel beim Titel aus `<div class="col-md-3 column-left">Dramaturgie</div>` neu `<div class="col-md-3 column-left" id="dramaturgie">Dramaturgie</div>` machen (also eine id einfügen) und dann ganz oben im Inhaltsverzeichnis `<a href="#dramaturgie">Dramaturgie</a>` [→ Anchor](https://www.rapidtables.com/web/html/link/html-anchor-link.html)

das mit der nummer 69420 kannte ich noch nicht...
Hast du deine Domain in der Zwischenzeit reservieren können?

Wenn du einen  Kommentar oder ein Problem hast, bitte hier antworten.

**Comment by pascaleva** [comment]
Hallo Stefan
Danke für deine Bemerkungen. 
Stimmt, ich bin wirklich noch nicht fertig und wollte einige von dir angetönten Dinge auch noch angehen. Die Domain konnte ich nun doch noch reservieren. Hab mich auf dem iPhone registrieren und die Domain einrichten können :-)
